// Package email provides a Starlark module that sends email through the Resend
// API (https://resend.com). It is an L4 starpkg domain module: a thin, simple
// abstraction over a common online service, with one local touch point
// (reading host files for attachments).
//
// The module exposes a single additional builtin, send(), alongside the
// config setters/getters generated by the underlying configurable module
// (set_resend_api_key, set_sender_domain, get_sender_domain). send() returns a
// starlarkstruct with the following fields describing the outcome:
//   - success: bool, whether the email was sent successfully
//   - error: error message if sending failed, else None
//   - id: the unique identifier of the sent email, else None
//   - sender: the resolved sender address (from field), else None
//   - to: list of recipient addresses, else None
//   - cc: list of CC recipient addresses, else None
//   - bcc: list of BCC recipient addresses, else None
//   - reply_to: the reply-to address, else None
//   - subject: the email subject, else None
//   - body_html: the HTML content of the email, else None
//   - body_text: the plain text content of the email, else None
//   - attachments: list of attachment dicts (name, content), else None
//
// On failure success is False and every field other than success and error is
// None.
package email

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/1set/gut/ystring"
	"github.com/1set/starlet"
	"github.com/1set/starlet/dataconv"
	"github.com/1set/starlet/dataconv/types"
	"github.com/resend/resend-go/v2"
	"github.com/samber/lo"
	"github.com/starpkg/base"
	"go.starlark.net/starlark"
	"go.starlark.net/starlarkstruct"
)

// ModuleName defines the expected name for this module when used in Starlark's load() function, e.g., load('email', 'send')
const ModuleName = "email"

// Configuration key constants
const (
	configKeyResendAPIKey = "resend_api_key"
	configKeySenderDomain = "sender_domain"
)

var (
	none  = starlark.None // none is a convenience variable for starlark.None
	empty string          // empty is a convenience variable for an empty string
)

// Module wraps the ConfigurableModule with specific functionality for sending emails.
type Module struct {
	cfgMod *base.ConfigurableModule
	ext    *base.ConfigurableModuleExt
}

// NewModule creates a new instance of Module with default empty configurations.
func NewModule() *Module {
	return newModuleWithOptions(
		genConfigOption(configKeyResendAPIKey, "Resend API key", empty).SetSecret(true),
		genConfigOption(configKeySenderDomain, "Sender domain", empty),
	)
}

// NewModuleWithConfig creates a new instance of Module with the given configuration values.
func NewModuleWithConfig(resendAPIKey, senderDomain string) *Module {
	return newModuleWithOptions(
		genConfigOption(configKeyResendAPIKey, "Resend API key with preset value", resendAPIKey).SetSecret(true),
		genConfigOption(configKeySenderDomain, "Sender domain with preset value", senderDomain),
	)
}

// genConfigOption creates a configuration option with common settings.
// It sets up the name, description, default value, and environment variable, and marks it as secret if needed.
func genConfigOption(name, description, defaultValue string) *base.ConfigOption[string] {
	return base.NewConfigOption(defaultValue).
		WithName(name).
		WithDescription(description).
		WithEnvVar(strings.ToUpper(ModuleName + "_" + name))
}

// newModuleWithOptions creates a Module with the given configuration options.
func newModuleWithOptions(apiKeyOpt, senderDomainOpt *base.ConfigOption[string]) *Module {
	cm, _ := base.NewConfigurableModuleWithConfigOptions(
		apiKeyOpt,
		senderDomainOpt,
	)
	return &Module{
		cfgMod: cm,
		ext:    cm.Extend(),
	}
}

// LoadModule returns the Starlark module loader with the email-specific functions.
func (m *Module) LoadModule() starlet.ModuleLoader {
	// Additional module functions
	additionalFuncs := starlark.StringDict{
		"send": m.genSendFunc(),
	}
	return m.cfgMod.LoadModule(ModuleName, additionalFuncs)
}

// stringListToStarlark converts a slice of strings to a Starlark list of strings
func stringListToStarlark(strs []string) starlark.Value {
	return starlark.NewList(lo.Map(strs, func(s string, _ int) starlark.Value { return starlark.String(s) }))
}

// sendArgs holds the parsed, string-form arguments to send().
type sendArgs struct {
	subject       string
	bodyHTML      string
	bodyText      string
	to, cc, bcc   []string
	senderAddress string
	fromNameID    string
	replyAddress  string
	replyNameID   string
}

// composeRequest validates the arguments and assembles a Resend send request.
// It performs no I/O, so it is unit-testable; attachments and transport are
// handled by the caller.
func composeRequest(a sendArgs, senderDomain string) (*resend.SendEmailRequest, error) {
	if ystring.IsBlank(a.bodyHTML) && ystring.IsBlank(a.bodyText) {
		return nil, fmt.Errorf("one of html or text must be non-blank")
	}
	if len(a.to) == 0 {
		return nil, fmt.Errorf("to must be set and non-empty")
	}
	if ystring.IsBlank(a.senderAddress) && ystring.IsBlank(a.fromNameID) {
		return nil, fmt.Errorf("one of sender or from_id must be non-blank")
	}
	sendAddr, err := resolveAddress(a.senderAddress, a.fromNameID, senderDomain, "from_id")
	if err != nil {
		return nil, err
	}
	replyAddr, err := resolveAddress(a.replyAddress, a.replyNameID, senderDomain, "reply_id")
	if err != nil {
		return nil, err
	}
	return &resend.SendEmailRequest{
		From:    sendAddr,
		To:      a.to,
		Cc:      a.cc,
		Bcc:     a.bcc,
		ReplyTo: replyAddr,
		Subject: a.subject,
		Html:    a.bodyHTML,
		Text:    a.bodyText,
	}, nil
}

// resolveAddress returns the direct address, or builds one from a name id plus
// the sender domain. It returns an empty string when neither is provided (valid
// for the optional reply address).
func resolveAddress(direct, nameID, domain, idField string) (string, error) {
	if ystring.IsNotBlank(direct) {
		return direct, nil
	}
	if ystring.IsNotBlank(nameID) {
		if ystring.IsBlank(domain) {
			return "", fmt.Errorf("%s should be set when %s is used", configKeySenderDomain, idField)
		}
		return nameID + "@" + domain, nil
	}
	return "", nil
}

// genSendFunc generates the Starlark callable function to send an email.
func (m *Module) genSendFunc() starlark.Callable {
	return starlark.NewBuiltin(ModuleName+".send", func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
		// Load config: resend_api_key is required, sender_domain is optional
		resendAPIKey := m.ext.GetString(configKeyResendAPIKey)
		if resendAPIKey == "" {
			return none, fmt.Errorf("%s is not set", configKeyResendAPIKey)
		}
		// Get sender domain, but don't require it yet - it's only needed for from_id/reply_id
		senderDomain := m.ext.GetString(configKeySenderDomain, "")

		// parse args
		newOneOrListStr := func() *types.OneOrMany[starlark.String] { return types.NewOneOrManyNoDefault[starlark.String]() }
		var (
			subject            types.StringOrBytes         // must be set
			bodyHTML           types.NullableStringOrBytes // one of the two must be set
			bodyText           types.NullableStringOrBytes
			toAddresses        = newOneOrListStr() // must be set
			ccAddresses        = newOneOrListStr()
			bccAddresses       = newOneOrListStr()
			senderAddress      types.NullableStringOrBytes // one of the two must be set
			fromNameID         types.NullableStringOrBytes
			replyAddress       types.NullableStringOrBytes // both are optional
			replyNameID        types.NullableStringOrBytes
			attachmentFiles    = newOneOrListStr()
			attachmentContents = types.NewOneOrManyNoDefault[*starlark.Dict]()
		)
		if err := starlark.UnpackArgs(b.Name(), args, kwargs,
			"subject", &subject,
			"html?", &bodyHTML, "text?", &bodyText,
			"to", toAddresses, "cc?", ccAddresses, "bcc?", bccAddresses,
			"sender?", &senderAddress, "from_id?", &fromNameID,
			"reply_to?", &replyAddress, "reply_id?", &replyNameID,
			"attachment_file?", attachmentFiles, "attachment?", attachmentContents); err != nil {
			return none, err
		}

		// validate and assemble the request (pure, testable)
		convGoString := func(v []starlark.String) []string {
			l := make([]string, len(v))
			for i, vv := range v {
				l[i] = dataconv.StarString(vv)
			}
			return l
		}
		req, err := composeRequest(sendArgs{
			subject:       subject.GoString(),
			bodyHTML:      bodyHTML.GoString(),
			bodyText:      bodyText.GoString(),
			to:            convGoString(toAddresses.Slice()),
			cc:            convGoString(ccAddresses.Slice()),
			bcc:           convGoString(bccAddresses.Slice()),
			senderAddress: senderAddress.GoString(),
			fromNameID:    fromNameID.GoString(),
			replyAddress:  replyAddress.GoString(),
			replyNameID:   replyNameID.GoString(),
		}, senderDomain)
		if err != nil {
			return none, err
		}

		// for attachments
		if fps := attachmentFiles.Slice(); len(fps) > 0 {
			// load file content and attach
			for _, r := range fps {
				fp := r.GoString()
				c, err := os.ReadFile(fp)
				if err != nil {
					return none, err
				}
				n := filepath.Base(fp)
				req.Attachments = append(req.Attachments, &resend.Attachment{
					Filename: n,
					Content:  c,
				})
			}
		}
		if dcts := attachmentContents.Slice(); len(dcts) > 0 {
			// convert dict to attachment and attach
			for _, r := range dcts {
				fn, ok, err := r.Get(starlark.String("name"))
				if !ok || err != nil {
					return none, fmt.Errorf("attachment must have a name")
				}
				ct, ok, err := r.Get(starlark.String("content"))
				if !ok || err != nil {
					return none, fmt.Errorf("attachment must have content")
				}
				req.Attachments = append(req.Attachments, &resend.Attachment{
					Filename: dataconv.StarString(fn),
					Content:  []byte(dataconv.StarString(ct)),
				})
			}
		}

		// send it
		ctx := dataconv.GetThreadContext(thread)
		client := resend.NewClient(resendAPIKey)
		sent, err := client.Emails.SendWithContext(ctx, req)

		// Create response fields with success/error status
		fields := starlark.StringDict{
			"success": starlark.Bool(err == nil),
		}
		if err != nil {
			fields["error"] = starlark.String(err.Error())
			fields["id"] = none
			fields["sender"] = none
			fields["to"] = none
			fields["cc"] = none
			fields["bcc"] = none
			fields["reply_to"] = none
			fields["subject"] = none
			fields["body_html"] = none
			fields["body_text"] = none
		} else {
			fields["error"] = none
			fields["id"] = starlark.String(sent.Id)
			fields["sender"] = starlark.String(req.From)
			fields["to"] = stringListToStarlark(req.To)
			fields["cc"] = stringListToStarlark(req.Cc)
			fields["bcc"] = stringListToStarlark(req.Bcc)
			fields["reply_to"] = starlark.String(req.ReplyTo)
			fields["subject"] = starlark.String(req.Subject)
			fields["body_html"] = starlark.String(req.Html)
			fields["body_text"] = starlark.String(req.Text)
		}

		// Add attachments if present
		if len(req.Attachments) > 0 {
			attachments := make([]starlark.Value, len(req.Attachments))
			for i, att := range req.Attachments {
				attDict := starlark.NewDict(2)
				attDict.SetKey(starlark.String("name"), starlark.String(att.Filename))
				attDict.SetKey(starlark.String("content"), starlark.Bytes(att.Content))
				attachments[i] = attDict
			}
			fields["attachments"] = starlark.NewList(attachments)
		} else {
			fields["attachments"] = none
		}
		return starlarkstruct.FromStringDict(starlarkstruct.Default, fields), nil
	})
}
